import './styles/main.css';
import AwcAlert from './components/awc-alert/awc-alert';
import AwcIcon from './components/awc-icon/awc-icon';
import AwcIconLoader from './components/awc-icon-loader/awc-icon-loader';
import AwcAccordion from './components/awc-accordion/awc-accordion';
import AwcAccordionItem from './components/awc-accordion/awc-accordion-item/awc-accordion-item';
import AwcTooltip from './components/awc-tooltip/awc-tooltip';
import AwcPopover from './components/awc-popover/awc-popover';
import AwcChips from './components/awc-chips/awc-chips';
import AwcAvatar from './components/awc-avatar/awc-avatar';
import AwcAvatarBadge from './components/awc-avatar/awc-avatar-badge/awc-avatar-badge';
import AwcAvatarGroup from './components/awc-avatar/awc-avatar-group/awc-avatar-group';
import AwcButton from './components/forms/awc-button/awc-button';
import AwcCheckboxGroup from './components/forms/awc-checkbox-group/awc-checkbox-group';
import AwcCheckbox from './components/forms/awc-checkbox-group/awc-checkbox/awc-checkbox';
import AwcSelect from './components/forms/awc-select/awc-select';
import AwcSelectItem from './components/forms/awc-select/awc-select-item/awc-select-item';
declare const _default: {
    AwcAlert: typeof AwcAlert;
    AwcIcon: typeof AwcIcon;
    AwcIconLoader: typeof AwcIconLoader;
    AwcAccordion: typeof AwcAccordion;
    AwcAccordionItem: typeof AwcAccordionItem;
    AwcTooltip: typeof AwcTooltip;
    AwcButton: typeof AwcButton;
    AwcCheckboxGroup: typeof AwcCheckboxGroup;
    AwcCheckbox: typeof AwcCheckbox;
    AwcPopover: typeof AwcPopover;
    AwcSelect: typeof AwcSelect;
    AwcSelectItem: typeof AwcSelectItem;
    AwcChips: typeof AwcChips;
    AwcAvatar: typeof AwcAvatar;
    AwcAvatarBadge: typeof AwcAvatarBadge;
    AwcAvatarGroup: typeof AwcAvatarGroup;
};
export default _default;
